JRNS-2: First screen + Coordinators + Dynamic colors
iOS-vk-education/2022_1s_Journeys pull request #11
Opened 2022-11-10 20:26 UTC by v0blaa

2022-11-10 20:36 UTC, v0blaa commented
зачем нам координатор, спросите вы.
а я отвечу: вдруг мы потом сделаем таббар!

2022-11-13 17:38 UTC, NaR0RoW requested changes
See comments

2022-11-13 17:38 UTC, NaR0RoW commented on Podfile.lock
> +COCOAPODS: 1.11.3
Почему решила Podfile воспользоваться, а не SPM например, просто интересуюсь

2022-11-13 17:38 UTC, NaR0RoW commented on Podfile.lock
> +  - SnapKit (= 5.6.0)
Ты уверена, что хочешь с помощью SnapKit верстать? 
Мне лично кажется, что в начале лучше стандартные ресурсы изучить, а потом уже к готовым решениям переходить

2022-11-13 17:38 UTC, NaR0RoW commented on Journeys/SceneDelegate.swift
>      func sceneDidDisconnect(_ scene: UIScene) {
Лучше удалить методы, которые не используются

2022-11-13 17:38 UTC, NaR0RoW commented on Journeys/SceneDelegate.swift
> +
Если в else блоке один return, то лучше в одну строчку выражение записывать

2022-11-13 17:38 UTC, NaR0RoW commented on Journeys/Modules/TripsCells/TripCell.swift
> +protocol TripCellDeledate: AnyObject {
typo: TripCellDeledate -> TripCellDelegate

2022-11-13 17:38 UTC, NaR0RoW commented on Journeys/Modules/TripsCells/TripCell.swift
> +            static let wigth: CGFloat = 14.0
typo: wigth -> width

2022-11-13 17:38 UTC, NaR0RoW commented on Journeys/Modules/TripsCells/TripCell.swift
> +        struct DatesLabel {
Перед объявлением новой структуры лучше делать перенос строки

2022-11-13 17:38 UTC, NaR0RoW commented on Journeys/Modules/TripsCells/TripCell.swift
> +    struct Constants {
Лучше назвать TripCellConstants, так понятнее будет

2022-11-13 17:38 UTC, NaR0RoW commented on Journeys/Modules/TripsCells/TripCell.swift
> +        isInFavourites = !isInFavourites
Если я правильно понял, то лучше воспользоваться методом .toggle(), т.е.  isInFavourites.toggle()

2022-11-13 17:38 UTC, NaR0RoW commented on Journeys/Modules/TripsCells/TripCell.swift
> +    private func setupSubiews() {
typo: setupSubiews -> setupSubviews

2022-11-13 17:38 UTC, NaR0RoW commented on Journeys/Modules/TripsCells/TripCell.swift
> +    // MARK: Private properties
Уже не properties, а functions

2022-11-13 17:38 UTC, NaR0RoW commented on Journeys/Modules/TripsCells/TripCell.swift
> +    private let picture = UIImageView()
Посмотри в сторону `Anonymous Closures`. Это конечно субъективно, но мне лично кажется, что так лучше и удобнее объявлять переменные 
```
private let favoriteButton: UIButton = {
        let button = UIButton()
        button.createShadowButtonWithSystemImage(with: "heart.circle.fill")
        button.translatesAutoresizingMaskIntoConstraints = false
        
        return button
    }()
```

2022-11-13 17:38 UTC, NaR0RoW commented on Journeys/Modules/TripsCells/AddTripCell.swift
> +    struct Constants {
Тут тоже лучше название поменять

2022-11-13 17:38 UTC, NaR0RoW commented on Journeys/Modules/TripsCells/AddTripCell.swift
> +        setupSubiews()
Опечатка

2022-11-13 17:38 UTC, NaR0RoW commented on Journeys/Modules/Trips/View/TripsViewController.swift
> +    struct Constants {
И тут

2022-11-13 17:38 UTC, NaR0RoW commented on Journeys/Modules/Trips/View/TripsViewController.swift
> +        return value(forKey: "statusBar") as? UIView
return можно опустить

2022-11-13 18:13 UTC, v0blaa commented on Podfile.lock
> +COCOAPODS: 1.11.3
Подами пользовалась до этого, а SPM лучше? Не интересовалась просто

2022-11-13 18:14 UTC, v0blaa commented on Podfile.lock
> +  - SnapKit (= 5.6.0)
я якорями верстала до этого, могу к ним вернуться, если это принципиально

2022-11-13 18:15 UTC, v0blaa commented on Journeys/Modules/TripsCells/TripCell.swift
> +protocol TripCellDeledate: AnyObject {
непонела

2022-11-14 16:44 UTC, NaR0RoW commented on Podfile.lock
> +  - SnapKit (= 5.6.0)
> я якорями верстала до этого, могу к ним вернуться, если это принципиально

Если базовыми инструментами хорошо владеешь, то можно спокойно на SnapKite верстать

2022-11-14 16:46 UTC, NaR0RoW commented on Podfile.lock
> +COCOAPODS: 1.11.3
> Подами пользовалась до этого, а SPM лучше? Не интересовалась просто

Нельзя однозначно сказать, что лучше, а что нет.
Поды конечно намного стабильнее, но не такие удобные как SPM. 
Это конечно все субъективно, юзай то, что тебе нравится. 
Просто если с подами ты уже плотно поработала, может имеет смысл SPM немного потрогать? Лишним точно не будет

2022-11-14 17:06 UTC, NaR0RoW requested changes
1. Предлагаю `SwiftLint` в проект добавить 
2. Поставь следующую галочку, чтобы грамматических ошибок в словах не допускать // `Edit -> Format -> Spelling and Grammar -> Check spelling while typing`
3. Я бы вообще избавился от `enum Constants`. Мне кажется, что они ухудшают читабельность. Конечно, если переменная используется во многих VC, то лучше в отдельную сущность ее значение вынести, но мне кажется, что сейчас это не очень выглядит.
4. Нужно папки в порядок привести:. В VIPER модель называется entity. Лучше не TripsViewIO, а полным именем называть. И ты вроде на модули проект разбила, но TripsCells почему-то не Trips модуле находятся

2022-11-17 12:33 UTC, v0blaa commented on Journeys/Coordinators/JourneysCoordinator.swift
> +//  Created by Сергей Адольевич on 09.11.2022.
это я

2022-11-17 12:38 UTC, v0blaa commented on Journeys/Modules/FloatingButton/FloatingButton.swift
> +//  Created by Сергей Адольевич on 10.11.2022.
мой папа, я на его рабочем ноуте все делаю)))

2022-11-22 11:04 UTC, merged