JRNS-21: Settings and account
iOS-vk-education/2022_1s_Journeys pull request #29
Opened 2023-03-22 14:46 UTC by v0blaa

2023-03-23 20:28 UTC, Devgen8 requested changes

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Coordinators/AccountCoordinator.swift
>          Auth.auth().addIDTokenDidChangeListener { (auth, user) in
[weak self] чтобы не создать retain cycle
https://stevenpcurtis.medium.com/retain-cycles-and-memory-management-in-swift-ed4aefedb01a

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Coordinators/AccountCoordinator.swift
> +    private var appCoordinator: AppCoordinatorProtocol
А для чего добавили?

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Coordinators/JourneysCoordinator.swift
>      func tripInfoModuleWantsToClose() {
Лучше в подобных методах делегатных использовать названия более напоминающие методы из жизненного цикла viewController'а (например, tripsInfoModuleWillClose, tripsInfoModuleDidClose, closeTripsInfoModuleIfNeeded). Это облегчает понимание кода, не приходится смотреть, где вызывается данный метод.

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Extencions/UIWindow.swift
> +//
Название папки Extensions видимо должно было быть

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Extencions/ViewControllerWithDimBackground.swift
> +    let backgroundView: UIView = {
private

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Modules/Account/View/AccountViewController.swift
> +        if let selectedIndexPath = tableView.indexPathForSelectedRow {
Лучше в didSelectRowAt deselect делать или хочется именно после возвращения на экран показывать анимацию?

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Modules/Account/View/AccountViewController.swift
> +            make.height.equalTo(250)
250 лучше в константы вынести

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Modules/Account/View/AccountViewController.swift
> +        1
Можно не прописывать, это значение по умолчанию

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Modules/Account/View/AccountViewController.swift
> +        guard let cell = tableView.dequeueReusableCell(withIdentifier: "SettingsCell",
SettingsCell строчкой в нескольких местах используется, так что лучше сделать константой и использовать ее

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Modules/AccountInfo/Presenter/AccountInfoPresenter.swift
> +        case personalInfo = 0
0 можно не прописывать, rawValues по умолчанию с 0 начинаются

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Modules/AccountInfo/Presenter/AccountInfoPresenter.swift
> +        guard Sections.allCases.indices.contains(section) else { return nil }
И тут

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Modules/Account/Presenter/AccountPresenter.swift
> +        guard SettingsCell.CellType.Account.allCases.indices.contains(indexPath.row) else { return }
Лучше манипулировать count для проверки, формирование списка индексов и поиск внутри него дороже обходится

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Modules/AccountInfo/Presenter/AccountInfoPresenter.swift
> +                return
Можно вынести из-под if-else, в обоих случаях выполняется

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Modules/Auth/Presenter/AuthPresenter.swift
> +        let row = indexPath.row == 2 ? 3 : indexPath.row
Тут как раз-таки лучше работать с опциями перечисления и их rawValues, потому что в индексах рано или поздно можно запутаться

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Modules/Auth/Presenter/AuthPresenter.swift
> +        if cellType == .email {
Проверка ни на что не влияет

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Modules/Auth/View/AuthViewController.swift
>      private func didTapContimueButton() {
Continue

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Modules/Auth/View/AuthViewController.swift
> +    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
Зачем переопределение?

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Modules/Auth/View/AuthViewController.swift
> +    func numberOfSections(in tableView: UITableView) -> Int {
Не нужно

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Modules/Auth/View/AuthViewIO.swift
> +import UIKit
Для чего import?

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Modules/Settings/Presenter/SettingsPresenter.swift
> +        notificationManager.hasUserEnabledNotificationsAtIOSLevel(completion: completion)
Может проверять наличие значения hasUserEnabledNotifications?

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Modules/Settings/View/SettingsViewController.swift
> +        if let selectedIndexPath = tableView.indexPathForSelectedRow {
Аналогичный вопрос

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Modules/Settings/View/SettingsViewController.swift
> +        let subjectEncoded = subject.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)!
Лучше через guard оформить, force unwrap не стоит использовать по возможности

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Modules/Settings/View/SettingsViewController.swift
> +        let gmailUrl = URL(string: "googlegmail://co?to=\(to)&subject=\(subjectEncoded)&body=\(bodyEncoded)")
Может при создании сразу и проверку на возможность открытия делать и возвращать, если нужно, чтобы лишних урлов не вводить заранее?

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Modules/SettingsSubModule/SettingsHelpers.swift
> +    var id: String {
Это что-то личное?)

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Modules/SettingsSubModule/SettingsSubViewModel.swift
> +        print(localizationSystem.getLanguage())
Это можно удалить, судя по всему

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/SceneDelegate.swift
> +let themeWindow = ThemeWindow()
А это зачем?

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Services/AppRateManager.swift
> +        } else {
А зачем тогда else?)

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Services/NotificationManager.swift
> +        hasUserEnabledNotificationsAtIOSLevel()  { result in
Лучше, наверное, как-то вроде isEnabled назвать, а то result не сразу понятно что из себя представляет

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/Services/NotificationManager.swift
> +                })
Может вынесем в отдельную функцию? А то эта объемная какая-то получается

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/SwiftUI+Common/RoundedCornerShape.swift
> +import SwiftUI
Не нужно

2023-03-23 20:28 UTC, Devgen8 commented on Journeys/SwiftUI+Common/TrackableScrollView.swift
> +    let content: Content
private

2023-03-29 22:10 UTC, v0blaa commented on Journeys/Modules/Auth/Presenter/AuthPresenter.swift
> +        let row = indexPath.row == 2 ? 3 : indexPath.row
тут никак иначе, ибо используется rawValue еще и на экране аккаунта, где не нужно ячейку нового пароля скипать

2023-03-29 22:21 UTC, v0blaa commented on Journeys/Modules/Settings/View/SettingsViewController.swift
> +        let gmailUrl = URL(string: "googlegmail://co?to=\(to)&subject=\(subjectEncoded)&body=\(bodyEncoded)")
без понятия...

2023-03-29 22:21 UTC, v0blaa commented on Journeys/Modules/SettingsSubModule/SettingsHelpers.swift
> +    var id: String {
??

2023-04-02 19:51 UTC, Devgen8 requested changes

2023-04-02 19:51 UTC, Devgen8 commented on Journeys/Extensions/ViewControllerWithDimBackground.swift
>      let backgroundView: UIView = {
Я так понял, что эта вью не private, потому что нужна для subclass'ов, лучше тогда ее сделать хотя бы private(set)

2023-04-02 19:51 UTC, Devgen8 commented on Journeys/Modules/AccountInfo/Presenter/AccountInfoPresenter.swift
> +        if newEmail != nil && newEmail != email {
Перечисление условий через запятую делает проще чтение условия, особенно если бы условий было бы 3-4 как по мне + сравнение с nil можно опускать в таких случаях. Дело вкуса, но я бы так написал:
if newEmail, newEmail != email

2023-04-02 19:51 UTC, Devgen8 commented on Journeys/Modules/AccountInfo/Presenter/AccountInfoPresenter.swift
> +    }
Кажется лишней вся эта структура. Обычно просто сравнивают новые данные со старыми: если они совпадают, то сохранять ничего не нужно, если отличаются, то сохраняем

2023-04-02 19:51 UTC, Devgen8 commented on Journeys/Modules/AccountInfo/View/AccountInfoViewController.swift
> +    func clearCellsTextFields(in section: Int) {
Если вдруг случится ошибка какая-то со второй ячейкой, например, то у первой и третьей не очистятся поля из-за выхода из функции

2023-04-06 06:03 UTC, Devgen8 requested changes

2023-04-06 06:03 UTC, Devgen8 commented on Journeys/Modules/AccountInfo/Model/AccountInfoModel.swift
> +                    if let completion { completion() }
completion?()

2023-04-06 06:03 UTC, Devgen8 commented on Journeys/Modules/AccountInfo/Presenter/AccountInfoPresenter.swift
> +                          confirmPassword: confirmPassword)
А зачем 2 раза сохранение пароля?

2023-04-06 06:03 UTC, Devgen8 commented on Journeys/Modules/AccountInfo/Presenter/AccountInfoPresenter.swift
> +        if let newEmail, newEmail != currentEmail {
Из названия методов кажется, что email/пароль будут сохранены, но на самом деле внутри проверка на необходимость сохранения. Тут тогда лучше либо назвать метод как-то вроде saveUsersEmailIfNeeded, либо делать проверку на совпадение email'а/пароля за пределами функции.

2023-04-10 22:07 UTC, merged