mvp+firebase
iOS-vk-education/2022_1s_Journeys pull request #30
Opened 2023-04-09 15:44 UTC by linlinich

2023-04-15 08:13 UTC, Devgen8 requested changes

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/AppDelegate.swift
> +        //YMKMapKit.setLocale("ru_RU")
Актуально?

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/Coordinators/EventsCoordinator.swift
> +    private let loadingViewGroup = DispatchGroup()
Не вижу, где используются

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/Coordinators/EventsCoordinator.swift
>      func start() {
Имена start и finish слабо помогают понять, что происходит в этом классе. Если кто-то решит переиспользовать этот код, то ему будет сложновато разобраться, так что лучше какие-то более говорящие имена давать

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/Coordinators/EventsCoordinator.swift
> +    func usualEventsModuleWantsToOpenAddEventVC() {
Кажется название метода можно сократить до openAddEventVC, так как нам не важно, кто это хочет

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/Coordinators/EventsCoordinator.swift
> +//        navigationController.pushViewController(eventsViewController, animated: true)
Тут и выше удаляем комменты?

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/AddingEventViewController.swift
> -    // MARK: Public properties
А для чего тут и ниже вплотную функции/переменные размещаются?

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/AddingEventViewController.swift
> +    var time = ""
Вот это все лучше сделать отдельной структурой, тем более если в твоей архитектуре это view, то оно не должно хранить данные. Оно должно лишь передавать модели данные от пользователя, а потом получать новые данные от модели и размещать в UI элементах.

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/AddingEventViewController.swift
> +        let startDate = calendarCell.dateChanged()
dateChanged - не очень подходящее название для метода, который возвращает дату из ячейки. Лучше назвать как-то вроде selectedDate

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/AddingEventViewController.swift
> +        guard let calendarCell = collectionView.cellForItem(at: IndexPath(row: 0, section: 6)) as? TimeCell else {
Выше тоже была calendarCell, в чем отличие?

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/AddingEventViewController.swift
> +        if calendar.date(from: startDateComponents)! > calendar.date(from: endDateComponents)! {
В этом нет необходимости, так как даты можно сравнить просто как startDate > endDate. И опять же, работа с данными должна быть внутри модели, задача View лишь в том, чтобы собрать эти данные со своих ui элементов и передать их модели

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/AddingEventViewController.swift
> +        let jj = eventTypeCell1?.returnPhoto()
Функция returnPhoto() ничего не возвращает, но я так понимаю тут пока не закончена до конца функциональность

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/AddingEventViewController.swift
> +        if indexPath.section == 7 || indexPath.section == 8{
Пробел перед фигурной скобкой

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/AddingEventViewController.swift
> +        return 10
Лучше вынести значение в константы, это и для проверок попадания в диапазон имеющихся секций удобно

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/AddingEventViewController.swift
> +                placeholder: "Кв/офис"), delegate: self)
Когда получается много однотипного кода - это хороший повод задуматься над тем, как его можно параметризовать, чтобы не писать каждый раз. Например, тут можно сделать словарь с ключом в виде номера секции, а значения в виде displayData'ы и настраивать ячейку за счет него

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/AddressViewObject.swift
> +struct AddressViewObjects {
Судя по методам в других файлах, это лучше назвать AddressPoint, например, так как с View тут нет никакой связи, да и объектов тоже нет.

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Adress.swift
>  struct Adress {
Address

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Adress.swift
> +    init?(dict: [String: Any], id: String) {
Слово dict можно использовать как внутреннюю переменную, но тот, кто вызывает этот конструктор не должен видеть его, лучше чтобы он вызывал более читаемый метод, например, init(withDictionary:), тогда сигнатура будет init(withDictionary dict: ...)

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Adress.swift
> +            let coordinates = dict["coordinates"] as? GeoPoint
Ключи словарей тоже лучше в константы выделять

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Cells/AddPhotoCell.swift
> +    func configureSetImage(image: UIImage) {
Тут лучше configureAddPhotoButton

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Cells/DateCell.swift
> +    func getDates() -> [Date]? {
Лучше в методах не использовать слово get. В Swift обычно оно и так подразумевается

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Cells/DateCell.swift
> +        return array
В таких методах можно здорово поупражняться в использовании высокоуровневых функций, которыми славится Swift. Про них хорошо рассказано в этой книжке, советую на будущее:
https://www.objc.io/books/advanced-swift/

Как пример, весь этот код можно сократить до
guard let numberOfDays = Calendar.current.dateComponents([.day], from: from, to: to).day, numberOfDays > 0 else { return [] }
    return (0..<numberOfDays).compactMap { Calendar.current.date(byAdding: .day, value: $0, to: from) }

Меньше разных проверок + ушли от Force unwrap, который может уронить приложение

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Cells/DateCell.swift
> +        if arrivalDate != nil && departureDate != nil {
В Swift есть множество способов распаковать опционал.
https://medium.com/@MarcStevenCoder/various-ways-to-unwrap-an-optional-in-swift-dcfe8188225

Тут не самый удачный способ получается: во-первых, пришлось из-за исходной проверки сдвигать код вправо, что при большем количестве условий приводит к усложнению читаемости, так что тут лучше использовать guard. Во-вторых, после проверки нам все еще приходится пользоваться Force unwrap. Как вариант можно вот так делать проверку в самом начале и дальше спокойно пользоваться переменными
guard let arrivalDate, let departureDate else { return }

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Cells/DateCell.swift
> +            datesRange = [firstDate!]
Аналогично про опционалы

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Cells/DateCell.swift
> +        if firstDate != nil && lastDate == nil {
Тут вроде firstDate уже всегда будет неравно nil из-за проверки выше

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Cells/DateCell.swift
> +        if firstDate != nil && lastDate != nil {
Тоже лучше guard использовать

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Cells/DescriptionCell.swift
> +        inpField.text = ""
Это не по умолчанию так?

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Cells/DescriptionCell.swift
> +    private var delegate: DescriptionCellDelegate!
А если не никто не присвоит делегат? Будет падение

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Cells/DescriptionCell.swift
> +        descriptionLabel.font = UIFont.systemFont(ofSize: 22.0, weight: .bold)
Может это просто в создании Label'а прописать?

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Cells/DescriptionCell.swift
> +            make.top.equalToSuperview().inset(50)
50 лучше в константы вынести как остальные значения

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Cells/DescriptionCell.swift
> +        return inputField.text!
Лучше вернуть "", если текст отсутствует

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Cells/DescriptionCell.swift
> +}
Это где-то используется?

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Cells/TimeCell.swift
> +    private var date : String!
Не стоит рисковать)

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Cells/TimeCell.swift
> +        datePicker.locale = Locale(identifier: localeID!)
Лучше распаковать

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Cells/TimeCell.swift
> +        datePicker.minimumDate = Calendar.current.date(byAdding: .year, value: 0, to: Date())
value: 0? Получается дата не меняется

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Cells/TimeCell.swift
> +        datePicker.locale = Locale(identifier: localeID!)
Аналогично

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Cells/TimeCell.swift
> +    var time : Date = .now
private

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/Cells/TimeCell.swift
> +            contentView.addSubview(datePicker)
Лишний сдвиг

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/EventsModuleIO.swift
> +    func usualEventsModuleWantsToOpenAddEventVC()
По поводу названия отписывал ранее

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/EventsPresenter.swift
> +import UIKit
В Presenter рановато UIKit импортировать, он только во View появляется)

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/EventsService.swift
> +            let events = documents.compactMap { Adress(dict: $0.data(), id: $0.documentID) }
Лайк за compactMap)

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/EventsViewController.swift
> +            let image1 = UIImage(asset: Asset.Assets.PlacemarkIcons.defaultPlacemark)
image1 не особо дает понять для чего переменная)
Лучше переименовать и одновременно сделать распаковку опционала, чтобы в следующей строке Force unwrap не использовать

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/SuggestionViewController.swift
> +        tableView.autoSetDimension(.height, toSize: CGFloat(SuggestionViewControllerConstants.TableView.height))
Может сразу константы сделать типа CGFloat, чтобы потом не преобразовывать?

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/SuggestionViewController.swift
> +    let boundingBox = YMKBoundingBox( // Москва
Удачный комментарий, помогает понять, что вообще за константы

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/SuggestionViewController.swift
> +    let suggestOptions = YMKSuggestOptions(suggestTypes: .geo, userPosition: nil, suggestWords: true)
private?

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/SuggestionViewController.swift
> +        var adress : String
address

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/SuggestionViewController.swift
> +        (adress, area) = splitAdress(suggestResult: suggestResults[path.row].displayText ?? " ")
Можно сразу написать let (address, area) и не объявлять переменные выше

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/SuggestionViewController.swift
> +        if #available(iOS 16.0, *) {
Во-первых, не вижу тут чего-то специфического для iOS 16, так что вроде эта проверка не нужна. Во-вторых, какой-то очень-очень специфический парсинг строки и кажется, что все тут может поломаться при малейшем изменении suggest'а. Чтобы можно было это хорошо проревьювить и самое главное, чтобы это в дальнейшем можно было поправить если что, надо оставить комментарии о том, какую строку он парсит и в каждой строке подписать, что мы получаем после выполнения команды. На такие вещи лучше писать тесты)

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/SuggestionViewController.swift
> +        (adress, area) = splitAdress(suggestResult: suggestResults[indexPath.row].displayText ?? " ")
Аналогично про объявление переменных

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/SuggestionViewController.swift
> +        viewController.address = cell.address.text!
Распаковываем

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/SuggestionViewController.swift
> +        geocoder.geocodeAddressString(suggestResults[indexPath.row].displayText!) {
И тут

2023-04-15 08:13 UTC, Devgen8 commented on Journeys/EventsViews/SuggestionViewController.swift
> +            print(type(of: lat))
Можно убрать?

2023-05-16 20:32 UTC, Devgen8 requested changes

2023-05-16 20:32 UTC, Devgen8 commented on Journeys/AddingEvent/AddingEventViewController.swift
> +        guard let calendarCell = collectionView.cellForItem(at: IndexPath(row: 0, section: 6)) as? TimeCell else {
Как-то странно, что и это, и ячейка выше - обе calendarCell

2023-05-16 20:32 UTC, Devgen8 commented on Journeys/AddingEvent/AddingEventViewController.swift
> +        let eventDescriptionCell1 = collectionView.cellForItem(at: IndexPath(row: 0, section: 7)) as? DescriptionCell
А зачем 1?

2023-05-16 20:32 UTC, Devgen8 commented on Journeys/AddingEvent/AddingEventViewController.swift
> +        output?.saveData(post: post, coordinates: coordinates!, eventImage: eventImage ?? UIImage(asset: Asset.Assets.tripsPlaceholder)!)
Лучше через guard

2023-05-16 20:32 UTC, Devgen8 commented on Journeys/AddingEvent/AddingEventViewController.swift
> +extension AddingEventViewController: PlacemarkCellDelegate {
А зачем быть делегатом, который никак не реагирует на события?

2023-05-16 20:32 UTC, Devgen8 commented on Journeys/AddingEvent/AddingEventViewController.swift
> +extension AddingEventViewController: UIImagePickerControllerDelegate {
Аналогично

2023-05-16 20:32 UTC, Devgen8 commented on Journeys/AddingEvent/AddingEventViewController.swift
> +    func showAlert1(title: String, message: String) {
Тут тоже к чему 1?

2023-05-16 20:32 UTC, Devgen8 commented on Journeys/AddingEvent/AddingPresenter.swift
> +        model.storeAddingData(event: post, eventImage: eventImage ?? UIImage(asset: Asset.Assets.tripsPlaceholder)!, coordinatesId: "jdjd")
Уходим от Force unwrap + jdjd - так и задумано?

2023-05-16 20:32 UTC, Devgen8 commented on Journeys/Events/EventViewObject.swift
> +    var adress: String
address

2023-05-16 20:32 UTC, Devgen8 commented on Journeys/Events/EventViewObject.swift
> +struct EventViewObjectmmm {
MMM?)
![image](https://github.com/iOS-vk-education/2022_1-2s_Journeys/assets/56021020/2ff1167e-ce73-49d5-860f-9d1e089e7850)

2023-05-16 20:32 UTC, Devgen8 commented on Journeys/Events/EventsViewObject.swift
> +    var adress: String
address

2023-05-16 20:32 UTC, Devgen8 commented on Journeys/SingleEvent/BottomSheet/BottomSheetTransitioningDelegate.swift
> +        )
А для чего этот метод, если есть системные свойства presented/presentingVC?

2023-05-21 22:22 UTC, linlinich commented on Journeys/EventsViews/Cells/TimeCell.swift
> +        datePicker.minimumDate = Calendar.current.date(byAdding: .year, value: 0, to: Date())
это значит, что минимальную дату можно задать начиная с настоящего момента, не раньше

2023-05-27 14:05 UTC, merged