JRNS-22: Currency and Events in trip info module
iOS-vk-education/2022_1s_Journeys pull request #31
Opened 2023-04-13 18:48 UTC by v0blaa

2023-05-03 21:45 UTC, v0blaa commented
Сейчас готова вся логика, осталось локализацию добавить и скелетончики прикрутить

2023-05-13 19:31 UTC, Devgen8 requested changes

2023-05-13 19:31 UTC, Devgen8 commented on Journeys/Models/Location.swift
> +    }
Как вариант можно еще подобным образом description переопределять, чтобы и при дебаге, например, значение структуры в таком формате печаталось

2023-05-13 19:31 UTC, Devgen8 commented on Journeys/Models/Location.swift
> +        lhs.country == rhs.country && lhs.city == rhs.city ? true : false
А для чего часть с ? true : false ?

2023-05-13 19:31 UTC, Devgen8 commented on Journeys/Models/NetworkModels/GeoData.swift
> +    var longitude: Double
Не стоит константами сделать? Кроме конструктора как-то их можно менять?

2023-05-13 19:31 UTC, Devgen8 commented on Journeys/Models/Place.swift
> +    var countryCode: String
И тут может константами сделать?

2023-05-13 19:31 UTC, Devgen8 commented on Journeys/Models/Weather.swift
> +        return false
Можно просто условие прописать и тогда не понадобится if и return true/false

2023-05-13 19:31 UTC, Devgen8 commented on Journeys/Modules/TripInfo/PlacesInfo/Interactor/PlacesInfoInteractorIO.swift
> +    func noCoordunates(for location: Location)
noCoordinates

2023-05-13 19:31 UTC, Devgen8 commented on Journeys/Modules/Trips/TripsCells/Skeleton/SkeletonLoadable.swift
> +//}
Задел на будущее?

2023-05-13 19:31 UTC, Devgen8 commented on Journeys/Network/Services/NetworkRequestFactory.swift
> +            return URLRequest(url: URL(string: "")!)
Может лучше nil возвращать?

2023-05-13 19:31 UTC, Devgen8 commented on mapCell.patch
> +diff --git a/Journeys/Modules/TripInfo/PlacesInfo/View/Cells/EventMapCell/EventMapCell.swift b/Journeys/Modules/TripInfo/PlacesInfo/View/Cells/EventMapCell/EventMapCell.swift
Видимо это лишний файл)

2023-05-19 19:24 UTC, Devgen8 approved these changes

2023-05-19 23:37 UTC, merged