Bottom sheet
iOS-vk-education/2022_1s_Journeys pull request #35
Opened 2023-05-22 07:11 UTC by linlinich

2023-05-24 06:31 UTC, Devgen8 requested changes

2023-05-24 06:31 UTC, Devgen8 commented on Journeys/AddingEvent/AddingEventViewController.swift
>  extension AddingEventViewController: AddingViewInput {
Все еще актуально расширение?

2023-05-24 06:31 UTC, Devgen8 commented on Journeys/AddingEvent/Cells/AddPhotoCell.swift
> +    var editImage: UIImage?
Нигде не используется

2023-05-24 06:31 UTC, Devgen8 commented on Journeys/AddingEvent/Cells/DescriptionCell.swift
> +        }
Для коротких условий можно тернарным оператором пользоваться
text == "" ? L10n.descriptionIsMissing : text

2023-05-24 06:31 UTC, Devgen8 commented on Journeys/AddingEvent/Cells/PlacemarkCell.swift
> +        return text
inputField.text ?? " "

2023-05-24 06:31 UTC, Devgen8 commented on Journeys/AddingEvent/Cells/TimeCell.swift
> +        guard let localeID = Locale.preferredLanguages.first else { return }
Тут прямо из функции надо вернуться, если localeId отсутствует? Тогда setupSubviews и др не будут вызваны

2023-05-24 06:31 UTC, Devgen8 commented on Journeys/AddingEvent/Cells/TimeCell.swift
> +        guard let localeID = Locale.preferredLanguages.first else { return }
Аналогично

2023-05-24 06:31 UTC, Devgen8 commented on Journeys/Coordinators/EventsCoordinator.swift
> +        //navigationController.pushViewController(svc, animated: false)
?

2023-05-24 06:31 UTC, Devgen8 commented on Journeys/Events/EventsPresenter.swift
> +        return (lalitude, longitude, zoom)
Если в функции только возвращается какое-то значение, слово return можно не писать

2023-05-24 06:31 UTC, Devgen8 commented on Journeys/Events/EventsViewController.swift
> +            placemark.setIconWith(placemarkImage)
Лучше не возвращаться из функции в таком случае, чтобы placemark был настроен до конца

2023-05-24 06:31 UTC, Devgen8 commented on Journeys/Events/SingleEvent/Cells/DurationCell.swift
> +    let sartTime: String
start

2023-05-24 06:31 UTC, Devgen8 commented on Journeys/SingleEvent/SingleEventModuleIO.swift
> +}
Нужен ли этот протокол, если в нем нет ни одного метода?

2023-05-24 06:31 UTC, Devgen8 commented on Journeys/SingleEvent/SingleEventViewController.swift
> +        return
Можно просто ничего не писать

2023-05-25 23:55 UTC, linlinich commented on Journeys/AddingEvent/AddingEventViewController.swift
>  extension AddingEventViewController: AddingViewInput {
нужно подписаться чтобы билдер работал

2023-05-27 06:26 UTC, Devgen8 approved these changes

2023-05-27 14:04 UTC, merged